# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtMultimediaWidgets import QCameraViewfinder
import res


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 1000)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1300, 1000))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.BoxCameraPreview = QtWidgets.QGroupBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(16)
        self.BoxCameraPreview.setFont(font)
        self.BoxCameraPreview.setObjectName("BoxCameraPreview")
        self.PreviewWidgt = QCameraViewfinder(self.BoxCameraPreview)
        self.PreviewWidgt.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.PreviewWidgt.setObjectName("PreviewWidgt")
        self.gridLayout.addWidget(self.BoxCameraPreview, 1, 0, 1, 1)
        self.BoxCapture = QtWidgets.QGroupBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(16)
        self.BoxCapture.setFont(font)
        self.BoxCapture.setObjectName("BoxCapture")
        self.ShowPhoto = QtWidgets.QLabel(self.BoxCapture)
        self.ShowPhoto.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.ShowPhoto.setObjectName("ShowPhoto")
        self.gridLayout.addWidget(self.BoxCapture, 1, 1, 1, 1)
        self.BoxInformation = QtWidgets.QGroupBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(16)
        self.BoxInformation.setFont(font)
        self.BoxInformation.setObjectName("BoxInformation")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.BoxInformation)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 1200, 200))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelID = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(16)
        self.labelID.setFont(font)
        self.labelID.setObjectName("labelID")
        self.gridLayout_2.addWidget(self.labelID, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        self.LabelName = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(16)
        self.LabelName.setFont(font)
        self.LabelName.setObjectName("LabelName")
        self.gridLayout_2.addWidget(self.LabelName, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 0, 1, 1)
        self.editTime = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.editTime.setObjectName("editTime")
        self.gridLayout_2.addWidget(self.editTime, 2, 3, 1, 2)
        self.editID = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.editID.setObjectName("editID")
        self.gridLayout_2.addWidget(self.editID, 0, 3, 1, 2)
        self.editName = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.editName.setObjectName("editName")
        self.gridLayout_2.addWidget(self.editName, 1, 3, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 0, 1, 1)
        self.labelTime = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(16)
        self.labelTime.setFont(font)
        self.labelTime.setObjectName("labelTime")
        self.gridLayout_2.addWidget(self.labelTime, 2, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 2, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 1, 5, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 2, 5, 1, 1)
        self.gridLayout_2.setColumnStretch(3, 1)
        self.gridLayout.addWidget(self.BoxInformation, 0, 0, 1, 2)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 879, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setAllowedAreas(QtCore.Qt.TopToolBarArea)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actCloseCamera = QtWidgets.QAction(MainWindow)
        self.actCloseCamera.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/remove_user.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actCloseCamera.setIcon(icon)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(16)
        self.actCloseCamera.setFont(font)
        self.actCloseCamera.setObjectName("actCloseCamera")
        self.actCapture = QtWidgets.QAction(MainWindow)
        self.actCapture.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/picture.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actCapture.setIcon(icon1)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(16)
        self.actCapture.setFont(font)
        self.actCapture.setObjectName("actCapture")
        self.actQuit = QtWidgets.QAction(MainWindow)
        self.actQuit.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/exit_24.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actQuit.setIcon(icon2)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(16)
        self.actQuit.setFont(font)
        self.actQuit.setObjectName("actQuit")
        self.actStartCamera_2 = QtWidgets.QAction(MainWindow)
        self.actStartCamera_2.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/video_chat.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actStartCamera_2.setIcon(icon3)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(16)
        self.actStartCamera_2.setFont(font)
        self.actStartCamera_2.setObjectName("actStartCamera_2")
        self.toolBar.addAction(self.actStartCamera_2)
        self.toolBar.addAction(self.actCloseCamera)
        self.toolBar.addAction(self.actCapture)
        self.toolBar.addAction(self.actQuit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BoxCameraPreview.setTitle(_translate("MainWindow", "摄像头预览"))
        self.BoxCapture.setTitle(_translate("MainWindow", "识别图片"))
        self.ShowPhoto.setText(_translate("MainWindow", "TextLabel"))
        self.BoxInformation.setTitle(_translate("MainWindow", "识别信息"))
        self.labelID.setText(_translate("MainWindow", "学号："))
        self.LabelName.setText(_translate("MainWindow", "姓名："))
        self.labelTime.setText(_translate("MainWindow", "时间："))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actCloseCamera.setText(_translate("MainWindow", "关闭摄像头"))
        self.actCloseCamera.setToolTip(_translate("MainWindow", "CloseCamera"))
        self.actCapture.setText(_translate("MainWindow", "摄像头拍照"))
        self.actCapture.setToolTip(_translate("MainWindow", "Take a photo"))
        self.actQuit.setText(_translate("MainWindow", "退出"))
        self.actQuit.setToolTip(_translate("MainWindow", "Exit"))
        self.actStartCamera_2.setText(_translate("MainWindow", "开启摄像头"))
        self.actStartCamera_2.setToolTip(_translate("MainWindow", "StartCamera"))

